import pandera.polars as pa
import polars as pl


# Fact events, generated by adapters
# Input to segment builder
class FactSchema(pa.DataFrameModel):
    timestamp: pl.Datetime
    source: str
    entity_id: str
    value: str
    quantity_type: str


# Output of segment builder:
# Entity segments with explicit [start, end)
class SegmentSchema(pa.DataFrameModel):
    start: pl.Datetime
    end: pl.Datetime = pa.Field(nullable=True)
    entity_id: str
    quantity_type: str
    final_state: str


class UsageSchema(pa.DataFrameModel):
    timestamp: pl.Datetime
    quantity_type: str
    count: float = pa.Field(coerce=True)
    site: str  # chi_uc, chi_tacc, kvm_tacc...
    collector_type: str  # legacy, current
