import pandera.polars as pa
import polars as pl


# Fact events, generated by adapters
# Input to segment builder
class FactSchema(pa.DataFrameModel):
    timestamp: pl.Datetime
    source: str
    entity_id: str
    value: str
    quantity_type: str


# Ourput of timeline builder:
# Sequence of state events
class TimelineSchema(pa.DataFrameModel):
    timestamp: pl.Datetime
    entity_id: str
    quantity_type: str
    final_state: str


class UsageSchema(pa.DataFrameModel):
    timestamp: pl.Datetime
    quantity_type: str
    count: int
